const orderConstants = {
    ORDER_LOADING: "ORDER_LOADING",

    GET_PRICES_SUCCESS: "GET_PRICES_SUCCESS",
    GET_PRICES_FAIL: "GET_PRICES_FAIL",

    POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS",
    POST_ORDER_FAIL: "POST_ORDER_FAIL",
};

export default orderConstants;
